package com.yourong.core.tc.model;

import java.math.BigDecimal;
import java.util.Date;

public class MemberRepayment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.member_id
	 * @mbggenerated
	 */
	private Long memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.max_repeat_amount
	 * @mbggenerated
	 */
	private BigDecimal maxRepeatAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.max_repayment_amount
	 * @mbggenerated
	 */
	private BigDecimal maxRepaymentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.transaction_id
	 * @mbggenerated
	 */
	private Long transactionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_repayment.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.id
	 * @return  the value of tc_member_repayment.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.id
	 * @param id  the value for tc_member_repayment.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.member_id
	 * @return  the value of tc_member_repayment.member_id
	 * @mbggenerated
	 */
	public Long getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.member_id
	 * @param memberId  the value for tc_member_repayment.member_id
	 * @mbggenerated
	 */
	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.max_repeat_amount
	 * @return  the value of tc_member_repayment.max_repeat_amount
	 * @mbggenerated
	 */
	public BigDecimal getMaxRepeatAmount() {
		return maxRepeatAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.max_repeat_amount
	 * @param maxRepeatAmount  the value for tc_member_repayment.max_repeat_amount
	 * @mbggenerated
	 */
	public void setMaxRepeatAmount(BigDecimal maxRepeatAmount) {
		this.maxRepeatAmount = maxRepeatAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.max_repayment_amount
	 * @return  the value of tc_member_repayment.max_repayment_amount
	 * @mbggenerated
	 */
	public BigDecimal getMaxRepaymentAmount() {
		return maxRepaymentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.max_repayment_amount
	 * @param maxRepaymentAmount  the value for tc_member_repayment.max_repayment_amount
	 * @mbggenerated
	 */
	public void setMaxRepaymentAmount(BigDecimal maxRepaymentAmount) {
		this.maxRepaymentAmount = maxRepaymentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.transaction_id
	 * @return  the value of tc_member_repayment.transaction_id
	 * @mbggenerated
	 */
	public Long getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.transaction_id
	 * @param transactionId  the value for tc_member_repayment.transaction_id
	 * @mbggenerated
	 */
	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.create_time
	 * @return  the value of tc_member_repayment.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.create_time
	 * @param createTime  the value for tc_member_repayment.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_repayment.update_time
	 * @return  the value of tc_member_repayment.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_repayment.update_time
	 * @param updateTime  the value for tc_member_repayment.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}