package com.yourong.core.tc.model;

import java.math.BigDecimal;
import java.util.Date;

public class MemberHistoryRepayment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.member_id
	 * @mbggenerated
	 */
	private Long memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.add_amount
	 * @mbggenerated
	 */
	private BigDecimal addAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.repeat_amount
	 * @mbggenerated
	 */
	private BigDecimal repeatAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.transaction_id
	 * @mbggenerated
	 */
	private Long transactionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tc_member_history_repayment.status
	 * @mbggenerated
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.id
	 * @return  the value of tc_member_history_repayment.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.id
	 * @param id  the value for tc_member_history_repayment.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.member_id
	 * @return  the value of tc_member_history_repayment.member_id
	 * @mbggenerated
	 */
	public Long getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.member_id
	 * @param memberId  the value for tc_member_history_repayment.member_id
	 * @mbggenerated
	 */
	public void setMemberId(Long memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.add_amount
	 * @return  the value of tc_member_history_repayment.add_amount
	 * @mbggenerated
	 */
	public BigDecimal getAddAmount() {
		return addAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.add_amount
	 * @param addAmount  the value for tc_member_history_repayment.add_amount
	 * @mbggenerated
	 */
	public void setAddAmount(BigDecimal addAmount) {
		this.addAmount = addAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.repeat_amount
	 * @return  the value of tc_member_history_repayment.repeat_amount
	 * @mbggenerated
	 */
	public BigDecimal getRepeatAmount() {
		return repeatAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.repeat_amount
	 * @param repeatAmount  the value for tc_member_history_repayment.repeat_amount
	 * @mbggenerated
	 */
	public void setRepeatAmount(BigDecimal repeatAmount) {
		this.repeatAmount = repeatAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.transaction_id
	 * @return  the value of tc_member_history_repayment.transaction_id
	 * @mbggenerated
	 */
	public Long getTransactionId() {
		return transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.transaction_id
	 * @param transactionId  the value for tc_member_history_repayment.transaction_id
	 * @mbggenerated
	 */
	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.create_time
	 * @return  the value of tc_member_history_repayment.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.create_time
	 * @param createTime  the value for tc_member_history_repayment.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.update_time
	 * @return  the value of tc_member_history_repayment.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.update_time
	 * @param updateTime  the value for tc_member_history_repayment.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tc_member_history_repayment.status
	 * @return  the value of tc_member_history_repayment.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tc_member_history_repayment.status
	 * @param status  the value for tc_member_history_repayment.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}