package com.yourong.core.ic.model;

import java.util.Date;
import java.math.BigDecimal;
//资产包基础类

public class ProjectPackage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.imgUrl
	 * @mbggenerated
	 */
	private String imgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.status
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.update_time
	 * @mbggenerated
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.total_amount
	 * @mbggenerated
	 */
	private BigDecimal totalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.total_count
	 * @mbggenerated
	 */
	private Integer totalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.max_annualized_rate
	 * @mbggenerated
	 */
	private BigDecimal maxAnnualizedRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.min_annualized_rate
	 * @mbggenerated
	 */
	private BigDecimal minAnnualizedRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.max_borrow_period
	 * @mbggenerated
	 */
	private Integer maxBorrowPeriod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.max_borrow_period_type
	 * @mbggenerated
	 */
	private Integer maxBorrowPeriodType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.min_borrow_period
	 * @mbggenerated
	 */
	private Integer minBorrowPeriod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.min_borrow_period_type
	 * @mbggenerated
	 */
	private Integer minBorrowPeriodType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.progress
	 * @mbggenerated
	 */
	private String progress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.sale_complated_time
	 * @mbggenerated
	 */
	private Date saleComplatedTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.audit_time
	 * @mbggenerated
	 */
	private Date auditTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.vote_amount
	 * @mbggenerated
	 */
	private BigDecimal voteAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.sale_start_time
	 * @mbggenerated
	 */
	private Date saleStartTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ic_project_package.sale_end_time
	 * @mbggenerated
	 */
	private Date saleEndTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.id
	 * @return  the value of ic_project_package.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.id
	 * @param id  the value for ic_project_package.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.imgUrl
	 * @return  the value of ic_project_package.imgUrl
	 * @mbggenerated
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.imgUrl
	 * @param imgurl  the value for ic_project_package.imgUrl
	 * @mbggenerated
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.name
	 * @return  the value of ic_project_package.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.name
	 * @param name  the value for ic_project_package.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.status
	 * @return  the value of ic_project_package.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.status
	 * @param status  the value for ic_project_package.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.create_time
	 * @return  the value of ic_project_package.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.create_time
	 * @param createTime  the value for ic_project_package.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.update_time
	 * @return  the value of ic_project_package.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.update_time
	 * @param updateTime  the value for ic_project_package.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.description
	 * @return  the value of ic_project_package.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.description
	 * @param description  the value for ic_project_package.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.total_amount
	 * @return  the value of ic_project_package.total_amount
	 * @mbggenerated
	 */
	public BigDecimal getTotalAmount() {
		return totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.total_amount
	 * @param totalAmount  the value for ic_project_package.total_amount
	 * @mbggenerated
	 */
	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.total_count
	 * @return  the value of ic_project_package.total_count
	 * @mbggenerated
	 */
	public Integer getTotalCount() {
		return totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.total_count
	 * @param totalCount  the value for ic_project_package.total_count
	 * @mbggenerated
	 */
	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.max_annualized_rate
	 * @return  the value of ic_project_package.max_annualized_rate
	 * @mbggenerated
	 */
	public BigDecimal getMaxAnnualizedRate() {
		return maxAnnualizedRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.max_annualized_rate
	 * @param maxAnnualizedRate  the value for ic_project_package.max_annualized_rate
	 * @mbggenerated
	 */
	public void setMaxAnnualizedRate(BigDecimal maxAnnualizedRate) {
		this.maxAnnualizedRate = maxAnnualizedRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.min_annualized_rate
	 * @return  the value of ic_project_package.min_annualized_rate
	 * @mbggenerated
	 */
	public BigDecimal getMinAnnualizedRate() {
		return minAnnualizedRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.min_annualized_rate
	 * @param minAnnualizedRate  the value for ic_project_package.min_annualized_rate
	 * @mbggenerated
	 */
	public void setMinAnnualizedRate(BigDecimal minAnnualizedRate) {
		this.minAnnualizedRate = minAnnualizedRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.max_borrow_period
	 * @return  the value of ic_project_package.max_borrow_period
	 * @mbggenerated
	 */
	public Integer getMaxBorrowPeriod() {
		return maxBorrowPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.max_borrow_period
	 * @param maxBorrowPeriod  the value for ic_project_package.max_borrow_period
	 * @mbggenerated
	 */
	public void setMaxBorrowPeriod(Integer maxBorrowPeriod) {
		this.maxBorrowPeriod = maxBorrowPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.max_borrow_period_type
	 * @return  the value of ic_project_package.max_borrow_period_type
	 * @mbggenerated
	 */
	public Integer getMaxBorrowPeriodType() {
		return maxBorrowPeriodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.max_borrow_period_type
	 * @param maxBorrowPeriodType  the value for ic_project_package.max_borrow_period_type
	 * @mbggenerated
	 */
	public void setMaxBorrowPeriodType(Integer maxBorrowPeriodType) {
		this.maxBorrowPeriodType = maxBorrowPeriodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.min_borrow_period
	 * @return  the value of ic_project_package.min_borrow_period
	 * @mbggenerated
	 */
	public Integer getMinBorrowPeriod() {
		return minBorrowPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.min_borrow_period
	 * @param minBorrowPeriod  the value for ic_project_package.min_borrow_period
	 * @mbggenerated
	 */
	public void setMinBorrowPeriod(Integer minBorrowPeriod) {
		this.minBorrowPeriod = minBorrowPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.min_borrow_period_type
	 * @return  the value of ic_project_package.min_borrow_period_type
	 * @mbggenerated
	 */
	public Integer getMinBorrowPeriodType() {
		return minBorrowPeriodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.min_borrow_period_type
	 * @param minBorrowPeriodType  the value for ic_project_package.min_borrow_period_type
	 * @mbggenerated
	 */
	public void setMinBorrowPeriodType(Integer minBorrowPeriodType) {
		this.minBorrowPeriodType = minBorrowPeriodType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.progress
	 * @return  the value of ic_project_package.progress
	 * @mbggenerated
	 */
	public String getProgress() {
		return progress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.progress
	 * @param progress  the value for ic_project_package.progress
	 * @mbggenerated
	 */
	public void setProgress(String progress) {
		this.progress = progress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.sale_complated_time
	 * @return  the value of ic_project_package.sale_complated_time
	 * @mbggenerated
	 */
	public Date getSaleComplatedTime() {
		return saleComplatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.sale_complated_time
	 * @param saleComplatedTime  the value for ic_project_package.sale_complated_time
	 * @mbggenerated
	 */
	public void setSaleComplatedTime(Date saleComplatedTime) {
		this.saleComplatedTime = saleComplatedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.audit_time
	 * @return  the value of ic_project_package.audit_time
	 * @mbggenerated
	 */
	public Date getAuditTime() {
		return auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.audit_time
	 * @param auditTime  the value for ic_project_package.audit_time
	 * @mbggenerated
	 */
	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.vote_amount
	 * @return  the value of ic_project_package.vote_amount
	 * @mbggenerated
	 */
	public BigDecimal getVoteAmount() {
		return voteAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.vote_amount
	 * @param voteAmount  the value for ic_project_package.vote_amount
	 * @mbggenerated
	 */
	public void setVoteAmount(BigDecimal voteAmount) {
		this.voteAmount = voteAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.sale_start_time
	 * @return  the value of ic_project_package.sale_start_time
	 * @mbggenerated
	 */
	public Date getSaleStartTime() {
		return saleStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.sale_start_time
	 * @param saleStartTime  the value for ic_project_package.sale_start_time
	 * @mbggenerated
	 */
	public void setSaleStartTime(Date saleStartTime) {
		this.saleStartTime = saleStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ic_project_package.sale_end_time
	 * @return  the value of ic_project_package.sale_end_time
	 * @mbggenerated
	 */
	public Date getSaleEndTime() {
		return saleEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ic_project_package.sale_end_time
	 * @param saleEndTime  the value for ic_project_package.sale_end_time
	 * @mbggenerated
	 */
	public void setSaleEndTime(Date saleEndTime) {
		this.saleEndTime = saleEndTime;
	}
}