package com.yourong.core.ic.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectPackageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public ProjectPackageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNull() {
            addCriterion("imgUrl is null");
            return (Criteria) this;
        }

        public Criteria andImgurlIsNotNull() {
            addCriterion("imgUrl is not null");
            return (Criteria) this;
        }

        public Criteria andImgurlEqualTo(String value) {
            addCriterion("imgUrl =", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotEqualTo(String value) {
            addCriterion("imgUrl <>", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThan(String value) {
            addCriterion("imgUrl >", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlGreaterThanOrEqualTo(String value) {
            addCriterion("imgUrl >=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThan(String value) {
            addCriterion("imgUrl <", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLessThanOrEqualTo(String value) {
            addCriterion("imgUrl <=", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlLike(String value) {
            addCriterion("imgUrl like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotLike(String value) {
            addCriterion("imgUrl not like", value, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlIn(List<String> values) {
            addCriterion("imgUrl in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotIn(List<String> values) {
            addCriterion("imgUrl not in", values, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlBetween(String value1, String value2) {
            addCriterion("imgUrl between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andImgurlNotBetween(String value1, String value2) {
            addCriterion("imgUrl not between", value1, value2, "imgurl");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNull() {
            addCriterion("total_amount is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNotNull() {
            addCriterion("total_amount is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountEqualTo(BigDecimal value) {
            addCriterion("total_amount =", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotEqualTo(BigDecimal value) {
            addCriterion("total_amount <>", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThan(BigDecimal value) {
            addCriterion("total_amount >", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount >=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThan(BigDecimal value) {
            addCriterion("total_amount <", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_amount <=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIn(List<BigDecimal> values) {
            addCriterion("total_amount in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotIn(List<BigDecimal> values) {
            addCriterion("total_amount not in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_amount not between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNull() {
            addCriterion("total_count is null");
            return (Criteria) this;
        }

        public Criteria andTotalCountIsNotNull() {
            addCriterion("total_count is not null");
            return (Criteria) this;
        }

        public Criteria andTotalCountEqualTo(Integer value) {
            addCriterion("total_count =", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotEqualTo(Integer value) {
            addCriterion("total_count <>", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThan(Integer value) {
            addCriterion("total_count >", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_count >=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThan(Integer value) {
            addCriterion("total_count <", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountLessThanOrEqualTo(Integer value) {
            addCriterion("total_count <=", value, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountIn(List<Integer> values) {
            addCriterion("total_count in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotIn(List<Integer> values) {
            addCriterion("total_count not in", values, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountBetween(Integer value1, Integer value2) {
            addCriterion("total_count between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andTotalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("total_count not between", value1, value2, "totalCount");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateIsNull() {
            addCriterion("max_annualized_rate is null");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateIsNotNull() {
            addCriterion("max_annualized_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateEqualTo(BigDecimal value) {
            addCriterion("max_annualized_rate =", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateNotEqualTo(BigDecimal value) {
            addCriterion("max_annualized_rate <>", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateGreaterThan(BigDecimal value) {
            addCriterion("max_annualized_rate >", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_annualized_rate >=", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateLessThan(BigDecimal value) {
            addCriterion("max_annualized_rate <", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_annualized_rate <=", value, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateIn(List<BigDecimal> values) {
            addCriterion("max_annualized_rate in", values, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateNotIn(List<BigDecimal> values) {
            addCriterion("max_annualized_rate not in", values, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_annualized_rate between", value1, value2, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxAnnualizedRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_annualized_rate not between", value1, value2, "maxAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateIsNull() {
            addCriterion("min_annualized_rate is null");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateIsNotNull() {
            addCriterion("min_annualized_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateEqualTo(BigDecimal value) {
            addCriterion("min_annualized_rate =", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateNotEqualTo(BigDecimal value) {
            addCriterion("min_annualized_rate <>", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateGreaterThan(BigDecimal value) {
            addCriterion("min_annualized_rate >", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("min_annualized_rate >=", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateLessThan(BigDecimal value) {
            addCriterion("min_annualized_rate <", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("min_annualized_rate <=", value, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateIn(List<BigDecimal> values) {
            addCriterion("min_annualized_rate in", values, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateNotIn(List<BigDecimal> values) {
            addCriterion("min_annualized_rate not in", values, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_annualized_rate between", value1, value2, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMinAnnualizedRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_annualized_rate not between", value1, value2, "minAnnualizedRate");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodIsNull() {
            addCriterion("max_borrow_period is null");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodIsNotNull() {
            addCriterion("max_borrow_period is not null");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodEqualTo(Integer value) {
            addCriterion("max_borrow_period =", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodNotEqualTo(Integer value) {
            addCriterion("max_borrow_period <>", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodGreaterThan(Integer value) {
            addCriterion("max_borrow_period >", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_borrow_period >=", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodLessThan(Integer value) {
            addCriterion("max_borrow_period <", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("max_borrow_period <=", value, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodIn(List<Integer> values) {
            addCriterion("max_borrow_period in", values, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodNotIn(List<Integer> values) {
            addCriterion("max_borrow_period not in", values, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodBetween(Integer value1, Integer value2) {
            addCriterion("max_borrow_period between", value1, value2, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("max_borrow_period not between", value1, value2, "maxBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeIsNull() {
            addCriterion("max_borrow_period_type is null");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeIsNotNull() {
            addCriterion("max_borrow_period_type is not null");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeEqualTo(Integer value) {
            addCriterion("max_borrow_period_type =", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeNotEqualTo(Integer value) {
            addCriterion("max_borrow_period_type <>", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeGreaterThan(Integer value) {
            addCriterion("max_borrow_period_type >", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_borrow_period_type >=", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeLessThan(Integer value) {
            addCriterion("max_borrow_period_type <", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeLessThanOrEqualTo(Integer value) {
            addCriterion("max_borrow_period_type <=", value, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeIn(List<Integer> values) {
            addCriterion("max_borrow_period_type in", values, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeNotIn(List<Integer> values) {
            addCriterion("max_borrow_period_type not in", values, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeBetween(Integer value1, Integer value2) {
            addCriterion("max_borrow_period_type between", value1, value2, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMaxBorrowPeriodTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("max_borrow_period_type not between", value1, value2, "maxBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodIsNull() {
            addCriterion("min_borrow_period is null");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodIsNotNull() {
            addCriterion("min_borrow_period is not null");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodEqualTo(Integer value) {
            addCriterion("min_borrow_period =", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodNotEqualTo(Integer value) {
            addCriterion("min_borrow_period <>", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodGreaterThan(Integer value) {
            addCriterion("min_borrow_period >", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_borrow_period >=", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodLessThan(Integer value) {
            addCriterion("min_borrow_period <", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodLessThanOrEqualTo(Integer value) {
            addCriterion("min_borrow_period <=", value, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodIn(List<Integer> values) {
            addCriterion("min_borrow_period in", values, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodNotIn(List<Integer> values) {
            addCriterion("min_borrow_period not in", values, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodBetween(Integer value1, Integer value2) {
            addCriterion("min_borrow_period between", value1, value2, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodNotBetween(Integer value1, Integer value2) {
            addCriterion("min_borrow_period not between", value1, value2, "minBorrowPeriod");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeIsNull() {
            addCriterion("min_borrow_period_type is null");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeIsNotNull() {
            addCriterion("min_borrow_period_type is not null");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeEqualTo(Integer value) {
            addCriterion("min_borrow_period_type =", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeNotEqualTo(Integer value) {
            addCriterion("min_borrow_period_type <>", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeGreaterThan(Integer value) {
            addCriterion("min_borrow_period_type >", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_borrow_period_type >=", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeLessThan(Integer value) {
            addCriterion("min_borrow_period_type <", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeLessThanOrEqualTo(Integer value) {
            addCriterion("min_borrow_period_type <=", value, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeIn(List<Integer> values) {
            addCriterion("min_borrow_period_type in", values, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeNotIn(List<Integer> values) {
            addCriterion("min_borrow_period_type not in", values, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeBetween(Integer value1, Integer value2) {
            addCriterion("min_borrow_period_type between", value1, value2, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andMinBorrowPeriodTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("min_borrow_period_type not between", value1, value2, "minBorrowPeriodType");
            return (Criteria) this;
        }

        public Criteria andProgressIsNull() {
            addCriterion("progress is null");
            return (Criteria) this;
        }

        public Criteria andProgressIsNotNull() {
            addCriterion("progress is not null");
            return (Criteria) this;
        }

        public Criteria andProgressEqualTo(String value) {
            addCriterion("progress =", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressNotEqualTo(String value) {
            addCriterion("progress <>", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressGreaterThan(String value) {
            addCriterion("progress >", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressGreaterThanOrEqualTo(String value) {
            addCriterion("progress >=", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressLessThan(String value) {
            addCriterion("progress <", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressLessThanOrEqualTo(String value) {
            addCriterion("progress <=", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressLike(String value) {
            addCriterion("progress like", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressNotLike(String value) {
            addCriterion("progress not like", value, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressIn(List<String> values) {
            addCriterion("progress in", values, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressNotIn(List<String> values) {
            addCriterion("progress not in", values, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressBetween(String value1, String value2) {
            addCriterion("progress between", value1, value2, "progress");
            return (Criteria) this;
        }

        public Criteria andProgressNotBetween(String value1, String value2) {
            addCriterion("progress not between", value1, value2, "progress");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeIsNull() {
            addCriterion("sale_complated_time is null");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeIsNotNull() {
            addCriterion("sale_complated_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeEqualTo(Date value) {
            addCriterion("sale_complated_time =", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeNotEqualTo(Date value) {
            addCriterion("sale_complated_time <>", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeGreaterThan(Date value) {
            addCriterion("sale_complated_time >", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sale_complated_time >=", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeLessThan(Date value) {
            addCriterion("sale_complated_time <", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("sale_complated_time <=", value, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeIn(List<Date> values) {
            addCriterion("sale_complated_time in", values, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeNotIn(List<Date> values) {
            addCriterion("sale_complated_time not in", values, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeBetween(Date value1, Date value2) {
            addCriterion("sale_complated_time between", value1, value2, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andSaleComplatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("sale_complated_time not between", value1, value2, "saleComplatedTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andVoteAmountIsNull() {
            addCriterion("vote_amount is null");
            return (Criteria) this;
        }

        public Criteria andVoteAmountIsNotNull() {
            addCriterion("vote_amount is not null");
            return (Criteria) this;
        }

        public Criteria andVoteAmountEqualTo(BigDecimal value) {
            addCriterion("vote_amount =", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountNotEqualTo(BigDecimal value) {
            addCriterion("vote_amount <>", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountGreaterThan(BigDecimal value) {
            addCriterion("vote_amount >", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vote_amount >=", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountLessThan(BigDecimal value) {
            addCriterion("vote_amount <", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vote_amount <=", value, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountIn(List<BigDecimal> values) {
            addCriterion("vote_amount in", values, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountNotIn(List<BigDecimal> values) {
            addCriterion("vote_amount not in", values, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vote_amount between", value1, value2, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andVoteAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vote_amount not between", value1, value2, "voteAmount");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIsNull() {
            addCriterion("sale_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIsNotNull() {
            addCriterion("sale_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeEqualTo(Date value) {
            addCriterion("sale_start_time =", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotEqualTo(Date value) {
            addCriterion("sale_start_time <>", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeGreaterThan(Date value) {
            addCriterion("sale_start_time >", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sale_start_time >=", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeLessThan(Date value) {
            addCriterion("sale_start_time <", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("sale_start_time <=", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIn(List<Date> values) {
            addCriterion("sale_start_time in", values, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotIn(List<Date> values) {
            addCriterion("sale_start_time not in", values, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeBetween(Date value1, Date value2) {
            addCriterion("sale_start_time between", value1, value2, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("sale_start_time not between", value1, value2, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIsNull() {
            addCriterion("sale_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIsNotNull() {
            addCriterion("sale_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeEqualTo(Date value) {
            addCriterion("sale_end_time =", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotEqualTo(Date value) {
            addCriterion("sale_end_time <>", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeGreaterThan(Date value) {
            addCriterion("sale_end_time >", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sale_end_time >=", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeLessThan(Date value) {
            addCriterion("sale_end_time <", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("sale_end_time <=", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIn(List<Date> values) {
            addCriterion("sale_end_time in", values, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotIn(List<Date> values) {
            addCriterion("sale_end_time not in", values, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeBetween(Date value1, Date value2) {
            addCriterion("sale_end_time between", value1, value2, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("sale_end_time not between", value1, value2, "saleEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ic_project_package
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ic_project_package
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}