package com.yourong.core.tc.dao;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.yourong.core.tc.model.MemberRepayment;

public interface MemberRepaymentMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	int insert(MemberRepayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	int insertSelective(MemberRepayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	MemberRepayment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(MemberRepayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tc_member_repayment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(MemberRepayment record);


    MemberRepayment selectByMemberId(@Param("memberId") Long memberId);
}